apiVersion: apps/v1
kind: Deployment
metadata:
  name: codemind-frontend
  namespace: codemind
  labels:
    app: codemind-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codemind-frontend
  template:
    metadata:
      labels:
        app: codemind-frontend
    spec:
      containers:
      - name: codemind-frontend
        image: ghcr.io/quantumlayerplatform-dev-ai/codemind-frontend:0.1.5
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://codemind-api:8000"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: codemind-frontend
  namespace: codemind
  labels:
    app: codemind-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: codemind-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: codemind-frontend-nodeport
  namespace: codemind
  labels:
    app: codemind-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    protocol: TCP
    name: http
  selector:
    app: codemind-frontend